apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok-config
data:
  ngrok.yml: |
    version: "2"
    authtoken: "TOKEN"
    tunnels:
      gitea:
        proto: http
        addr: gitea-http.default.svc.cluster.local:3000
        hostname: coherent-shrimp-nationally.ngrok-free.app
