redis-cluster:
  enabled: false
redis:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: mysql
      HOST: mysql
      NAME: gitea
      USER: root
      PASSWD: newpassword
      PORT: 3306
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level